# Cask
cask "alfred"
cask "alt-tab"
cask "amethyst"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "spotify"
cask "visual-studio-code"
cask "google-drive"
cask "notunes"

# Native tools
brew "fish"
brew "git"
brew "neovim"
brew "tmux"

# Dev utils
brew "ripgrep"
brew "fzf"
brew "jq"
brew "direnv"

# System tools
brew "pstree"
brew "tree"
brew "starship"
brew "stow"

# Utilities
brew "bitwarden-cli"

# Runtimes
brew "nodejs"
